- name: Installing Nginx
  hosts: web
  become: yes
  tasks:
    - name: Install Nginx
      ansible.builtin.yum:
        name: nginx
        state: absent
    - name: Enable Nginx
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: true






