- name: Installing Nginx
  hosts: web
  become: yes
  tasks:
    - name: Install Nginx
      ansible.builtin.yum:
        name: nginx
        state: installed
    - name: Enable Nginx
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: true
    - name: delete file
      ansible.builtin.file:
        path: /usr/share/nginx/html/
        state: absent
    - name: Installing zip
      ansible.builtin.get_url:
        url: https://roboshop-builds.s3.amazonaws.com/web.zip
        dest: /tmp/web.zip
    - name: Unarchive a file that is already on the remote machine
      ansible.builtin.unarchive:
        src: /usr/share/nginx/html/web.zip
        dest: /tmp/web.zip
        remote_src: yes
    - name: Restart Nginx Service
      systemd:
        name: nginx
        state: restarted
    





