- name: Installing Nginx
  hosts: web
  become: yes
  tasks:
    - name: Install Nginx
      ansible.builtin.yum:
        name: nginx
        state: installed
    - name: Enable Nginx
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: true
    - name: delete file
      ansible.builtin.file:
        path: /usr/share/nginx/html
        state: directory
    - name: create html directory
      ansible.builtin.file:
        path: /usr/share/nginx/html
        state: directory
    - name: Installing zip
      ansible.builtin.get_url:
        url: https://roboshop-builds.s3.amazonaws.com/web.zip
        dest: /tmp/
    - name: Unarchive a file that is already on the remote machine
      ansible.builtin.unarchive:
        src: /tmp/web.zip
        dest: /usr/share/nginx/html
        remote_src: yes
    - name: copy roboshop.conf
      ansible.builtin.copy:
        src: roboshop.conf
        dest: /etc/nginx/default.d/roboshop.conf
    - name: Restart Nginx Service
      systemd:
        name: nginx
        state: restarted
    





