- name: Installing Nginx
  hosts: web
  become: yes
  tasks:
    - name: Install Nginx
      ansible.builtin.yum:
        name: nginx
        state: installed
    - name: Enable Nginx
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: true
    - name: delete file
      ansible.builtin.file:
        path: /usr/share/nginx/html/
        state: absent





